{% set name = "pytest-skip-slow" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-skip-slow-{{ version }}.tar.gz
  sha256: 655ea5c748c72947e0d302334e7fa8ef99929257a2a2bc928f630ddb5a161d88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=6.2.0

test:
  imports:
    - pytest_skip_slow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/okken/pytest-skip-slow
  summary: A pytest plugin to skip `@pytest.mark.slow` tests by default.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
